import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE
} from '@/constants/navigation.constant'
import type { NavigationTree } from '@/@types/navigation'
import { ADMIN, CUSTOMER } from '@/constants/roles.constant'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        roles: [],
        subMenu: [],
    },
    {
        key: 'products',
        path: '',
        title: 'Products',
        translateKey: 'nav.products.products',
        icon: 'products',
        type: NAV_ITEM_TYPE_COLLAPSE,
        roles: [],
        subMenu: [
            {
                key: 'products.productsDashboard',
                path: '/products/products-dashboard',
                title: 'Dashboard',
                translateKey: 'nav.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN, CUSTOMER],
                subMenu: [],
            },
            {
                key: 'products.productsList',
                path: '/products/products-list',
                title: 'Products List',
                translateKey: 'nav.productsList',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN, CUSTOMER],
                subMenu: [],
            },
            // {
            //     key: 'products.productDetails',
            //     path: '/products/product-Details',
            //     title: 'Product Details',
            //     translateKey: 'nav.productDetails',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     roles: [ADMIN, CUSTOMER],
            //     subMenu: [],
            // },
            {
                key: 'products.productNew',
                path: '/products/product-new',
                title: 'New Product',
                translateKey: 'nav.productNew',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN],
                subMenu: [],
            },
            {
                key: 'products.productEdit',
                path: '/products/product-edit/:id',
                title: 'Edit Product',
                translateKey: 'nav.productEdit',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'orders',
        path: '',
        title: 'Orders',
        translateKey: 'nav.orders.orders',
        icon: 'order',
        type: NAV_ITEM_TYPE_COLLAPSE,
        roles: [],
        subMenu: [
            {
                key: 'orders.ordersDashboard',
                path: '/orders/orders-dashboard',
                title: 'Dashboard',
                translateKey: 'nav.dashboard',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN, CUSTOMER],
                subMenu: [],
            },
            {
                key: 'orders.ordersList',
                path: '/orders/orders-list',
                title: 'Orders List',
                translateKey: 'nav.ordersList',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN, CUSTOMER],
                subMenu: [],
            },
            // {
            //     key: 'orders.orderDetails',
            //     path: '/orders/order-details/:id',
            //     title: 'Order Details',
            //     translateKey: 'nav.orderDetails',
            //     icon: '',
            //     type: NAV_ITEM_TYPE_ITEM,
            //     roles: [ADMIN, CUSTOMER],
            //     subMenu: [],
            // },
            {
                key: 'orders.newOrder',
                path: '/orders/new-order',
                title: 'New Order',
                translateKey: 'nav.newOrder',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN, CUSTOMER],
                subMenu: [],
            },
            {
                key: 'orders.editOrder',
                path: '/orders/edit-order',
                title: 'Edit Order',
                translateKey: 'nav.editOrder',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN],
                subMenu: [],
            },
        ],
    },
    {
        key: 'cart',
        path: '',
        title: 'Cart',
        translateKey: 'nav.cart',
        icon: 'cart',
        type: NAV_ITEM_TYPE_COLLAPSE,
        roles: [ADMIN, CUSTOMER],
        subMenu: [
            {
                key: 'cart.cartScreen',
                path: '/cart/your-cart',
                title: 'Cart',
                translateKey: 'nav.cart',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                roles: [ADMIN],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
